In [1]:
import numpy as np

In [20]:
a = np.array([0,1,2,3,20,21,22,50,51,52])
b = np.array([0, 0, 1, 2, 2.2, 5, 10, 10, 10, 10, 9, 9.9, 10, 10, 10])
c = np.nonzero(b >= 10)[0]
c

array([ 6,  7,  8,  9, 12, 13, 14])

In [6]:
for i, c in enumerate(a):
    print(c+1 != a[(i+1)%len(a)] or c-1 != a[(i-1)%len(a)], c)

True 0
False 1
False 2
True 3
True 20
False 21
True 22
True 50
False 51
True 52


In [80]:
a = np.nonzero(np.array(ddd) < 5)[0]
d = list(filter(lambda x: x[1]+1 != a[(x[0]+1)%len(a)] or x[1]-1 != a[(x[0]-1)%len(a)], enumerate(a)))
print(list(zip(*d))[1])
e = [x for i, x in enumerate(a) if (x+1 != a[(i+1)%len(a)] or x-1 != a[(i-1)%len(a)])]
ee = list(zip(e[::2],e[1::2]))
print(ee)

(0, 442, 615, 696, 698, 808, 953, 1052, 1439)
[(0, 442), (615, 696), (698, 808), (953, 1052)]


In [84]:
test1 = np.array([x for i, x in enumerate(a) if (x+1 != a[(i+1)%len(a)])])
test2 = np.array([x for i, x in enumerate(a) if (x-1 != a[(i-1)%len(a)])])
#idxs = test2[]
test3 = [x for x in test1 if x not in test2]
print(test1)
print(test2)
ttt = [x for x in zip(test2, test1) if x[0]!=x[1]]
print(ttt)

[ 442  696  698  953 1439]
[   0  615  698  808 1052]
[(0, 442), (615, 696), (808, 953), (1052, 1439)]


In [86]:
step = (2 * np.pi) / 1440
for x in ttt:
    print(x)
    print(step * x[0], step * x[1])
    print(np.rad2deg((step * x[0]-np.pi)), np.rad2deg((step * x[1]-np.pi)))

(0, 442)
0.0 1.928588823453734
-180.0 -69.5
(615, 696)
2.6834437249412817 3.036872898470133
-26.249999999999996 -6.000000000000009
(808, 953)
3.5255650890285457 4.15824694287649
22.000000000000007 58.24999999999999
(1052, 1439)
4.590215932745087 6.278821984049601
83.00000000000003 179.75000000000003


In [200]:
def range2cart(ranges, idx, theta, step):
    x = pos_x + ranges[idx] * np.cos(step * idx)
    y = pos_y + ranges[idx] * np.sin(step * idx)
    cart = np.array([x, y])
    return cart
pos_x = -5
pos_y = -6
theta = np.pi/4
oi_mat = []
aux = [1, 2, 3, 4, 5, 6, 7, 8]
idx_list = [x for t in ttt for x in t]
a = np.empty((len(idx_list), 2))
print(a.shape)
for i, x in enumerate(aux):
    a[i, :] = range2cart(aux, i, theta, np.pi/4)
print(a)
print('test')

(8, 2)
[[ -4.          -6.        ]
 [ -3.58578644  -4.58578644]
 [ -5.          -3.        ]
 [ -7.82842712  -3.17157288]
 [-10.          -6.        ]
 [ -9.24264069 -10.24264069]
 [ -5.         -13.        ]
 [  0.65685425 -11.65685425]]
test


In [202]:
print(step * (1440/2) - np.pi)
print(step * 1)
print(1440 - 720)

0.0
0.004363323129985824


In [211]:
a = np.array([0, 0])
goal = np.array([6, 7])
b = np.array([[0, 1], [-2, -1], [5, 6], [0, 2], [4.8, 7]])
print(a - b)
print(((a - b)**2))
print(np.sqrt(np.sum((a - b)**2, axis=1)))
dist_po = np.linalg.norm((a - b), axis=1)
print(dist_po)
print(np.argmin(dist_po))
dist_og = np.linalg.norm((goal - b), axis=1)
print(dist_og)
print(np.argmin(dist_og))
dist_t = dist_og + dist_po
print(dist_t)
print(np.argmin(dist_t))

[[ 0.  -1. ]
 [ 2.   1. ]
 [-5.  -6. ]
 [ 0.  -2. ]
 [-4.8 -7. ]]
[[ 0.    1.  ]
 [ 4.    1.  ]
 [25.   36.  ]
 [ 0.    4.  ]
 [23.04 49.  ]]
[1.         2.23606798 7.81024968 2.         8.48763807]
[1.         2.23606798 7.81024968 2.         8.48763807]
0
[ 8.48528137 11.3137085   1.41421356  7.81024968  1.2       ]
4
[ 9.48528137 13.54977648  9.22446324  9.81024968  9.68763807]
2


In [14]:
import numpy as np
agn2g = np.deg2rad(45)
step = (2 * np.pi) / 1440
cont_idx = [(0, 442), (615, 696), (698, 808), (953, 1052)]
for region in cont_idx:
    lim_inf = step * region[0]
    lim_sup = step * region[1]
    if lim_inf <= agn2g <= lim_sup:
        print('TRUE')
    else:
        print('false')

TRUE
false
false
false


In [24]:
theta = np.pi/2
T0r = np.array([
                [np.cos(theta), -np.sin(theta), 0, 1.5],
                [np.sin(theta), np.cos(theta), 0, -4.7],
                [0, 0, 1, 0],
                [0, 0, 0, 1]
              ])
rangex_robot = 1 * np.cos(np.pi/720 * 343 - np.pi)
rangey_robot = 1 * np.sin(np.pi/720 * 343 - np.pi)
range_robot = np.array([rangex_robot, rangey_robot, 1, 1]).reshape(-1, 1)
range_world = (T0r @ range_vec).ravel()
range_world

array([ 2.49725019, -4.77410849,  1.        ,  1.        ])

In [42]:
ddd = [2.878427028656006, 2.865940570831299, 2.853616237640381, 2.8414511680603027, 2.8294432163238525, 2.8175899982452393, 2.8058886528015137, 2.794337272644043, 2.782933473587036, 2.771674871444702, 2.760559558868408, 2.7495851516723633, 2.7387497425079346, 2.72805118560791, 2.7174875736236572, 2.707056760787964, 2.6967570781707764, 2.686586380004883, 2.6765427589416504, 2.6666247844696045, 2.6568305492401123, 2.64715838432312, 2.637606382369995, 2.6281728744506836, 2.618856430053711, 2.6096553802490234, 2.6005682945251465, 2.5915932655334473, 2.5827293395996094, 2.573974609375, 2.5653276443481445, 2.5567872524261475, 2.548352003097534, 2.54002046585083, 2.5317914485931396, 2.5236635208129883, 2.5156352519989014, 2.5077056884765625, 2.499873399734497, 2.4921371936798096, 2.4844961166381836, 2.4769487380981445, 2.469494104385376, 2.4621307849884033, 2.4548580646514893, 2.4476747512817383, 2.440579652786255, 2.4335720539093018, 2.4266505241394043, 2.419814109802246, 2.413062334060669, 2.406393527984619, 2.3998074531555176, 2.3933024406433105, 2.386878252029419, 2.3805336952209473, 2.374267816543579, 2.3680801391601562, 2.361969232559204, 2.3559346199035645, 2.3499755859375, 2.3440911769866943, 2.33828067779541, 2.332543134689331, 2.326878070831299, 2.321284532546997, 2.3157618045806885, 2.310309410095215, 2.3049263954162598, 2.299612045288086, 2.294365882873535, 2.28918719291687, 2.2840750217437744, 2.279029369354248, 2.2740490436553955, 2.2691335678100586, 2.2642822265625, 2.2594947814941406, 2.254770517349243, 2.250108480453491, 2.2455086708068848, 2.2409701347351074, 2.23649263381958, 2.2320752143859863, 2.227717638015747, 2.223419427871704, 2.219180107116699, 2.214998960494995, 2.2108755111694336, 2.2068095207214355, 2.2028002738952637, 2.198847532272339, 2.194950580596924, 2.1911094188690186, 2.1873230934143066, 2.183591365814209, 2.1799137592315674, 2.1762900352478027, 2.172719717025757, 2.1692023277282715, 2.1657376289367676, 2.162325143814087, 2.1589643955230713, 2.1556551456451416, 2.1523969173431396, 2.1491897106170654, 2.1460325717926025, 2.14292573928833, 2.1398684978485107, 2.1368606090545654, 2.133901834487915, 2.1309919357299805, 2.1281304359436035, 2.125316858291626, 2.122551441192627, 2.119833469390869, 2.1171627044677734, 2.1145389080047607, 2.111961841583252, 2.109431266784668, 2.1069467067718506, 2.1045081615448, 2.1021153926849365, 2.0997679233551025, 2.097465753555298, 2.0952084064483643, 2.0929958820343018, 2.090827703475952, 2.0887038707733154, 2.0866241455078125, 2.0845882892608643, 2.0825958251953125, 2.0806469917297363, 2.0787415504455566, 2.076878786087036, 2.075059175491333, 2.073282241821289, 2.071547508239746, 2.0698554515838623, 2.0682053565979004, 2.0665972232818604, 2.065031051635742, 2.063506603240967, 2.062023639678955, 2.060581922531128, 2.0591816902160645, 2.0578224658966064, 2.056504249572754, 2.0552268028259277, 2.053990125656128, 2.0527939796447754, 2.05163836479187, 2.050523042678833, 2.049448013305664, 2.0484132766723633, 2.0474185943603516, 2.04646372795105, 2.045548677444458, 2.0446736812591553, 2.0438382625579834, 2.0430424213409424, 2.0422861576080322, 2.041569232940674, 2.0408918857574463, 2.0402538776397705, 2.0396549701690674, 2.039095401763916, 2.0385749340057373, 2.0380935668945312, 2.037651300430298, 2.037248134613037, 2.03688383102417, 2.0365586280822754, 2.0362722873687744, 2.036024808883667, 2.035816192626953, 2.035646438598633, 2.035515546798706, 2.035423517227173, 2.035370111465454, 2.035355567932129, 2.0353798866271973, 2.035443067550659, 2.0355451107025146, 2.0356857776641846, 2.035865306854248, 2.036083936691284, 2.0363411903381348, 2.036637544631958, 2.0369725227355957, 2.037346601486206, 2.037759780883789, 2.0382120609283447, 2.038703203201294, 2.039233446121216, 2.0398030281066895, 2.0404117107391357, 2.041059970855713, 2.0417473316192627, 2.0424740314483643, 2.0432403087615967, 2.04404616355896, 2.044891834259033, 2.045776844024658, 2.0467019081115723, 2.0476667881011963, 2.0486717224121094, 2.0497167110443115, 2.050801992416382, 2.051927328109741, 2.053093194961548, 2.0542995929718018, 2.055546760559082, 2.0568344593048096, 2.0581631660461426, 2.059532642364502, 2.060943603515625, 2.0623955726623535, 2.0638890266418457, 2.0654242038726807, 2.0670011043548584, 2.068619728088379, 2.0702803134918213, 2.0719833374023438, 2.073728561401367, 2.07551646232605, 2.0773470401763916, 2.0792205333709717, 2.08113694190979, 2.083096742630005, 2.0851001739501953, 2.0871472358703613, 2.089238166809082, 2.0913732051849365, 2.093552589416504, 2.095776319503784, 2.0980451107025146, 2.100358724594116, 2.102717638015747, 2.1051220893859863, 2.107572317123413, 2.1100683212280273, 2.1126105785369873, 2.115199565887451, 2.117835283279419, 2.1205179691314697, 2.1232478618621826, 2.126025676727295, 2.1288511753082275, 2.1317250728607178, 2.1346473693847656, 2.1376185417175293, 2.140638828277588, 2.1437087059020996, 2.1468281745910645, 2.1499979496002197, 2.1532182693481445, 2.156489133834839, 2.159811496734619, 2.1631853580474854, 2.1666109561920166, 2.17008900642395, 2.1736197471618652, 2.17720365524292, 2.1808409690856934, 2.1845321655273438, 2.1882777214050293, 2.192077875137329, 2.1959333419799805, 2.1998443603515625, 2.2038114070892334, 2.2078349590301514, 2.2119154930114746, 2.2160532474517822, 2.2202491760253906, 2.224503517150879, 2.2288167476654053, 2.233189344406128, 2.237621784210205, 2.242114782333374, 2.246668815612793, 2.25128436088562, 2.2559621334075928, 2.26070237159729, 2.2655060291290283, 2.2703733444213867, 2.2753052711486816, 2.2803022861480713, 2.2853646278381348, 2.2904934883117676, 2.295689344406128, 2.300952672958374, 2.3062844276428223, 2.311685085296631, 2.317155122756958, 2.322695732116699, 2.3283073902130127, 2.3339908123016357, 2.3397467136383057, 2.3455758094787598, 2.3514792919158936, 2.357457399368286, 2.363511085510254, 2.3696413040161133, 2.3758490085601807, 2.3821346759796143, 2.3884992599487305, 2.394943952560425, 2.4014692306518555, 2.408076286315918, 2.4147658348083496, 2.421539068222046, 2.428396701812744, 2.43533992767334, 2.4423696994781494, 2.4494869709014893, 2.456692695617676, 2.4639880657196045, 2.471374273300171, 2.4788522720336914, 2.4864232540130615, 2.4940881729125977, 2.5018484592437744, 2.509705066680908, 2.5176594257354736, 2.525712728500366, 2.5338661670684814, 2.542120933532715, 2.550478458404541, 2.5589401721954346, 2.567507266998291, 2.576181173324585, 2.584963321685791, 2.593855142593384, 2.602858304977417, 2.611974000930786, 2.621203899383545, 2.630549669265747, 2.640012741088867, 2.649595022201538, 2.6592979431152344, 2.6691231727600098, 2.679072618484497, 2.68914794921875, 2.6993508338928223, 2.709683656692505, 2.7201476097106934, 2.7307450771331787, 2.7414779663085938, 2.7523481845855713, 2.7633578777313232, 2.7745089530944824, 2.785804033279419, 2.7972447872161865, 2.808833599090576, 2.820573091506958, 2.832465171813965, 2.844512462615967, 2.856717348098755, 2.86908221244812, 2.8816099166870117, 2.8825433254241943, 2.8860154151916504, 2.9175446033477783, 2.9212324619293213, 2.9263882637023926, 2.9582066535949707, 2.962540864944458, 2.9670495986938477, 2.99894118309021, 3.006234884262085, 3.011416435241699, 3.0167791843414307, 3.049104928970337, 3.0547311305999756, 3.0871193408966064, 3.0970726013183594, 3.1034204959869385, 3.1099629402160645, 3.142880439758301, 3.14972186088562, 3.1620986461639404, 3.195499897003174, 3.2031219005584717, 3.2109549045562744, 3.244621753692627, 3.2527952194213867, 3.268098831176758, 3.3023393154144287, 3.31136417388916, 3.345806360244751, 3.355212926864624, 3.3648579120635986, 3.3996832370758057, 3.4185550212860107, 3.4291367530822754, 3.4646735191345215, 3.4756925106048584, 3.486976146697998, 3.5229978561401367, 3.545283555984497, 3.5576062202453613, 3.5944621562957764, 3.607288360595703, 3.6204111576080322, 3.6578691005706787, 3.6838700771331787, 3.698155164718628, 3.7365903854370117, 3.7514586448669434, 3.7666618824005127, 3.8058359622955322, 3.821664333343506, 3.8613498210906982, 3.8927524089813232, 3.9099462032318115, 3.9508373737335205, 3.9687440395355225, 4.010244846343994, 4.028900146484375, 4.064985752105713, 4.107870101928711, 4.128119945526123, 4.171728134155273, 4.192837238311768, 4.237216472625732, 4.259231090545654, 4.281743049621582, 4.324835300445557, 4.348786354064941, 4.395810604095459, 4.443288326263428, 4.468804359436035, 4.517286777496338, 4.543939113616943, 4.5934929847717285, 4.622620582580566, 4.673825740814209, 4.725614070892334, 4.755908489227295, 4.808971881866455, 4.862682819366455, 4.8950982093811035, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.908085346221924, 4.8721113204956055, 4.8230390548706055, 4.754066467285156, 4.707572937011719, 4.646736145019531, 4.58208703994751, 4.5612335205078125, 4.584347248077393, 4.5444135665893555, 4.526973724365234, 4.489080429077148, 4.401087760925293, 4.387265682220459, 4.351851463317871, 4.3597235679626465, 4.34600305557251, 4.332314491271973, 4.318657875061035, 4.326859474182129, 4.313305854797363, 4.299781799316406, 4.308242321014404, 4.272820949554443, 4.259382724761963, 4.2680583000183105, 4.232585430145264, 4.2414045333862305, 4.250341415405273, 4.237124443054199, 4.24625301361084, 4.255502223968506, 4.264873027801514, 4.274367332458496, 4.283985614776611, 4.293729305267334, 4.303599834442139, 4.313598155975342, 4.323725700378418, 4.333983898162842, 4.34437370300293, 4.354896545410156, 4.365553855895996, 4.376347541809082, 4.387278079986572, 4.398347854614258, 4.409557342529297, 4.420909404754639, 4.432404041290283, 4.44404411315918, 4.455830097198486, 4.467764377593994, 4.479848861694336, 4.49208402633667, 4.504472732543945, 4.517016410827637, 4.529716491699219, 4.542575359344482, 4.555594444274902, 4.568775653839111, 4.582120895385742, 4.595632076263428, 4.609311580657959, 4.6231608390808105, 4.637182712554932, 4.651378631591797, 4.665750503540039, 4.680301666259766, 4.695033073425293, 4.7099480628967285, 4.725048542022705, 4.7403364181518555, 4.755814552307129, 4.771485805511475, 4.787351608276367, 4.803415775299072, 4.819680213928223, 4.836147308349609, 4.85282039642334, 4.869701862335205, 4.886794567108154, 4.904101848602295, 5.0, 4.939370632171631, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.9134552478790283, 2.908129930496216, 2.902879238128662, 2.89770245552063, 2.89259934425354, 2.8875691890716553, 2.8181867599487305, 2.8134098052978516, 2.8087024688720703, 2.739962577819824, 2.735497236251831, 2.688502550125122, 2.684237480163574, 2.680036783218384, 2.675900459289551, 2.671827554702759, 2.6678178310394287, 2.6638708114624023, 2.6599860191345215, 2.656163215637207, 2.652401924133301, 2.6487016677856445, 2.64506196975708, 2.6414825916290283, 2.63796329498291, 2.6345033645629883, 2.6311025619506836, 2.627760648727417, 2.6244771480560303, 2.6212518215179443, 2.618084192276001, 2.614974021911621, 2.6119208335876465, 2.608924627304077, 2.605984926223755, 2.6031012535095215, 2.600273609161377, 2.597501516342163, 2.59478497505188, 2.59212327003479, 2.5895161628723145, 2.5869638919830322, 2.584465742111206, 2.582021474838257, 2.5796310901641846, 2.577294111251831, 2.5750105381011963, 2.572780132293701, 2.5706024169921875, 2.568477153778076, 2.5664045810699463, 2.5643839836120605, 2.562415361404419, 2.5604987144470215, 2.55863356590271, 2.5568199157714844, 2.5550575256347656, 2.5533459186553955, 2.5516855716705322, 2.5500757694244385, 2.5485167503356934, 2.5470080375671387, 2.5455496311187744, 2.5441412925720215, 2.54278302192688, 2.5414748191833496, 2.5402159690856934, 2.5390071868896484, 2.5378475189208984, 2.5367374420166016, 2.5356767177581787, 2.534665107727051, 2.5337026119232178, 2.5327892303466797, 2.5319244861602783, 2.531108856201172, 2.530341863632202, 2.529623508453369, 2.528953790664673, 2.528332471847534, 2.5277597904205322, 2.527235507965088, 2.526759624481201, 2.526332139968872, 2.5259528160095215, 2.5256218910217285, 2.56535005569458, 2.5651118755340576, 2.564922571182251, 2.56478214263916, 2.564690589904785, 2.564647912979126, 2.5646543502807617, 2.564709424972534, 2.5648136138916016, 2.5649666786193848, 2.565168619155884, 2.5654194355010986, 2.5657193660736084, 2.566068172454834, 2.5664660930633545, 2.566912889480591, 2.567409038543701, 2.5679543018341064, 2.5685486793518066, 2.569192409515381, 2.569885492324829, 2.5706279277801514, 2.5714197158813477, 2.572261095046997, 2.5731523036956787, 2.5740931034088135, 2.5750837326049805, 2.5761241912841797, 2.5772147178649902, 2.578355073928833, 2.5795459747314453, 2.580787181854248, 2.582078695297241, 2.583420753479004, 2.5848135948181152, 2.586257219314575, 2.587751865386963, 2.5892977714538574, 2.5908946990966797, 2.592543363571167, 2.634705066680908, 2.636484146118164, 2.6383159160614014, 2.6402008533477783, 2.662426710128784, 2.664433240890503, 2.6664936542510986, 2.6686079502105713, 2.670776844024658, 2.6730003356933594, 2.675278425216675, 2.6776113510131836, 2.679999828338623, 2.682443380355835, 2.6849429607391357, 2.6874983310699463, 2.731107711791992, 2.733816385269165, 2.7365827560424805, 2.7394068241119385, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.883810997009277, 4.870582580566406, 4.832064151763916, 4.813291549682617, 4.8012166023254395, 4.763564586639404, 4.752027988433838, 4.709643363952637, 4.672703742980957, 4.662146091461182, 4.647580146789551, 4.611391067504883, 4.601864814758301, 4.562402725219727, 4.553592681884766, 4.518174648284912, 4.509812355041504, 4.499182224273682, 4.46440315246582, 4.4549479484558105, 4.420616626739502, 4.4138641357421875, 4.378415584564209, 4.372311115264893, 4.338568210601807, 4.304285049438477, 4.298943519592285, 4.293848991394043, 4.27855110168457, 4.260112762451172, 4.241913318634033, 4.2239484786987305, 4.2062153816223145, 4.188709735870361, 4.171428680419922, 4.1543684005737305, 4.137526035308838, 4.1208977699279785, 4.104480266571045, 4.088270664215088, 4.072266101837158, 4.056463718414307, 4.040859699249268, 4.025452136993408, 4.010237216949463, 3.995213270187378, 3.980376958847046, 3.965725898742676, 3.9512572288513184, 3.9369685649871826, 3.9228572845458984, 3.908921003341675, 3.8951575756073, 3.8815643787384033, 3.8681392669677734, 3.854879856109619, 3.8417842388153076, 3.8288497924804688, 3.816074848175049, 3.803457021713257, 3.79099440574646, 3.7786850929260254, 3.766526937484741, 3.7545182704925537, 3.742656946182251, 3.7309412956237793, 3.719369411468506, 3.707939624786377, 3.6966500282287598, 3.6854989528656006, 3.674484968185425, 3.6636061668395996, 3.6528611183166504, 3.6422481536865234, 3.631765604019165, 3.6214120388031006, 3.6111862659454346, 3.601086139678955, 3.591110944747925, 3.581258773803711, 3.571528673171997, 3.5619187355041504, 3.5524280071258545, 3.5430550575256348, 3.5337986946105957, 3.524657726287842, 3.5156304836273193, 3.506716251373291, 3.4979135990142822, 3.4892213344573975, 3.4806385040283203, 3.472163677215576, 3.4637959003448486, 3.4555342197418213, 3.4473774433135986, 3.439324378967285, 3.4313740730285645, 3.42352557182312, 3.4157779216766357, 3.408130168914795, 3.400581121444702, 3.39313006401062, 3.3857760429382324, 3.3785181045532227, 3.3713552951812744, 3.3642866611480713, 3.357311725616455, 3.3504292964935303, 3.3436386585235596, 3.3369388580322266, 3.330329418182373, 3.3238091468811035, 3.317377805709839, 3.3110339641571045, 3.3047773838043213, 3.298607110977173, 3.292522668838501, 3.28652286529541, 3.2806077003479004, 3.274775743484497, 3.2690269947052, 3.2633602619171143, 3.25777530670166, 3.2522714138031006, 3.246847629547119, 3.2415037155151367, 3.236238956451416, 3.231052875518799, 3.225944757461548, 3.220913887023926, 3.2159600257873535, 3.211082696914673, 3.2062809467315674, 3.201554536819458, 3.1969029903411865, 3.1923255920410156, 3.187821865081787, 3.183391809463501, 3.1790342330932617, 3.1747491359710693, 3.1705360412597656, 3.1663942337036133, 3.162323474884033, 3.158323287963867, 3.154393434524536, 3.1505331993103027, 3.146742343902588, 3.1430203914642334, 3.13936710357666, 3.13578200340271, 3.1322648525238037, 3.128814935684204, 3.125432252883911, 3.1221163272857666, 3.1188669204711914, 3.1156833171844482, 3.112565755844116, 3.109513521194458, 3.1065266132354736, 3.103604316711426, 3.1007468700408936, 3.0979533195495605, 3.095224142074585, 3.0925583839416504, 3.089956045150757, 3.0874171257019043, 3.0849411487579346, 3.0825276374816895, 3.080176830291748, 3.077888011932373, 3.0756611824035645, 3.0734963417053223, 3.0713930130004883, 3.0693509578704834, 3.0673699378967285, 3.0654501914978027, 3.0635910034179688, 3.0617923736572266, 3.060054302215576, 3.0583763122558594, 3.0567586421966553, 3.0552008152008057, 3.0537025928497314, 3.0522642135620117, 3.0508852005004883, 3.049565553665161, 3.0483052730560303, 3.0471038818359375, 3.045961618423462, 3.0448782444000244, 3.043853759765625, 3.0428876876831055, 3.041980504989624, 3.0411317348480225, 3.0403411388397217, 3.03960919380188, 3.038935422897339, 3.0383198261260986, 3.037762403488159, 3.0372631549835205, 3.0368218421936035, 3.0364387035369873, 3.0361132621765137, 3.035845994949341, 3.0356366634368896, 3.035485029220581, 3.0353915691375732, 3.035355806350708, 3.0353777408599854, 3.0354578495025635, 3.035595655441284, 3.0357913970947266, 3.0360450744628906, 3.0363566875457764, 3.036726236343384, 3.037153959274292, 3.037639617919922, 3.0381832122802734, 3.038785219192505, 3.039445161819458, 3.040163516998291, 3.040940046310425, 3.0417752265930176, 3.0426688194274902, 3.0436208248138428, 3.0446314811706543, 3.045701026916504, 3.0468294620513916, 3.0480167865753174, 3.0492632389068604, 3.0505688190460205, 3.051933765411377, 3.053358316421509, 3.054842233657837, 3.0563862323760986, 3.0579898357391357, 3.0596535205841064, 3.06137752532959, 3.063161611557007, 3.0650064945220947, 3.0669121742248535, 3.068878650665283, 3.070906162261963, 3.072995185852051, 3.075145721435547, 3.077357769012451, 3.079631805419922, 3.081968069076538, 3.084366798400879, 3.0868279933929443, 3.0893521308898926, 3.0919394493103027, 3.094590187072754, 3.097304582595825, 3.1000828742980957, 3.1029253005981445, 3.105832099914551, 3.1088039875030518, 3.1118407249450684, 3.114942789077759, 3.1181106567382812, 3.121344566345215, 3.1246449947357178, 3.12801194190979, 3.13144588470459, 3.1349470615386963, 3.1385161876678467, 3.14215350151062, 3.1458592414855957, 3.1496336460113525, 3.153477430343628, 3.15739107131958, 3.161374568939209, 3.165428638458252, 3.169553518295288, 3.1737499237060547, 3.178018093109131, 3.182358503341675, 3.1867713928222656, 3.1912577152252197, 3.195817708969116, 3.2004518508911133, 3.205160617828369, 3.209944486618042, 3.21480393409729, 3.2197399139404297, 3.224752426147461, 3.229842185974121, 3.2350099086761475, 3.2402560710906982, 3.2455813884735107, 3.250986099243164, 3.2564711570739746, 3.2620370388031006, 3.2676844596862793, 3.273413896560669, 3.279226064682007, 3.2851216793060303, 3.2911012172698975, 3.297165870666504, 3.3033158779144287, 3.309551954269409, 3.3158750534057617, 3.3222858905792236, 3.328784942626953, 3.3353734016418457, 3.3420517444610596, 3.348820924758911, 3.3556816577911377, 3.3626348972320557, 3.3696811199188232, 3.376821756362915, 3.3840572834014893, 3.3913886547088623, 3.3988165855407715, 3.4063425064086914, 3.4139668941497803, 3.4216909408569336, 3.4295156002044678, 3.437441825866699, 3.4454705715179443, 3.4536027908325195, 3.4618399143218994, 3.470182418823242, 3.4786319732666016, 3.487189292907715, 3.4958555698394775, 3.5046322345733643, 3.5135200023651123, 3.5225205421447754, 3.531634569168091, 3.5408637523651123, 3.5502090454101562, 3.5596718788146973, 3.569253444671631, 3.5789551734924316, 3.588778495788574, 3.607093095779419, 3.6181793212890625, 3.6297056674957275, 3.6416687965393066, 3.654066324234009, 3.64284348487854, 3.631909132003784, 3.597064733505249, 3.5866215229034424, 3.5521128177642822, 3.517725944519043, 3.5079429149627686, 3.473855495452881, 3.464512586593628, 3.4554219245910645, 3.421780824661255, 3.4131038188934326, 3.3797082901000977, 3.3714282512664795, 3.3382575511932373, 3.3303580284118652, 3.2973921298980713, 3.289857864379883, 3.2825441360473633, 3.2498936653137207, 3.242924213409424, 3.210432291030884, 3.2037930488586426, 3.1714415550231934, 3.165119171142578, 3.1589982509613037, 3.1268725395202637, 3.1210505962371826, 3.0890231132507324, 3.0834882259368896, 3.0781431198120117, 3.0462822914123535, 3.041208028793335, 3.036317825317383, 3.0045907497406006, 2.9999563694000244, 2.995500326156616, 2.9638748168945312, 2.959660291671753, 2.928046941757202, 2.9240636825561523, 2.92025089263916, 2.91660737991333, 2.8850905895233154, 2.881661891937256, 2.878314733505249]